CREATE TABLE CLIENTE(
    CLIENTE_ID SERIAL  NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(30),
    ENDERECO VARCHAR(300) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CLIENTE_ID)
);



