create database yamanbank;
use yamanbank;

CREATE TABLE CLIENTE(
    CLIENTE_ID INTEGER NOT NULL SERIAL,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(30),
    ENDERECO VARCHAR(300) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CLIENTE_ID)
);

CREATE TABLE CONTA(
    NUMERO_CONTA INTEGER NOT NULL,
    AGENCIA INTEGER NOT NULL,
    SENHA VARCHAR(6) NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY(NUMERO_CONTA, AGENCIA));

CREATE TABLE PRODUTO_FINANCEIRO(
    PRODUTO_FINANCEIRO_ID INTEGER NOT NULL SERIAL,
    VALOR FLOAT,
    FK_NUMERO_CONTA INTEGER NOT NULL,
    FK_AGENCIA INTEGER NOT NULL,
    FK_TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL,
    CONSTRAINT PK_PRODUTO_FINANCEIERO PRIMARY KEY(PRODUTO_FINANCEIRO_ID)
);

CREATE TABLE TRANSACAO(
    TRANSACAO_ID INTEGER NOT NULL SERIAL,
    DATA_TRANSACAO DATE NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR FLOAT NOT NULL,
    FK_PRODUTO_FINANCEIRO INTEGER,
    CONSTRAINT PK_TRANSACAO PRIMARY KEY(TRANSACAO_ID)
);

CREATE TABLE TIPO_PRODUTO_FINANCEIRO(
    TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL SERIAL,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_PRODUTO_FINANCEIRO PRIMARY KEY (TIPO_PRODUTO_FINANCEIRO_ID)
);

ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID);
ALTER TABLE PRODUTO_FINANCEIRO ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_TIPO_PRODUTO_FINANCEIRO FOREIGN KEY (FK_TIPO_PRODUTO_FINANCEIRO_ID) REFERENCES TIPO_PRODUTO_FINANCEIRO (TIPO_PRODUTO_FINANCEIRO_ID);
ALTER TABLE PRODUTO_FINANCEIRO ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_CONTA FOREIGN KEY (FK_NUMERO_CONTA , FK_AGENCIA) REFERENCES CONTA(NUMERO_CONTA,AGENCIA);
ALTER TABLE TRANSACAO ADD CONSTRAINT FK_TRANSACAO_PRODUTO_FINANCEIRO FOREIGN KEY (FK_PRODUTO_FINANCEIRO) REFERENCES PRODUTO_FINANCEIRO(PRODUTO_FINANCEIRO_ID);

INSERT INTO CLIENTE(NOME, CPF, EMAIL, ENDERECO) VALUES ('Fernanda', '444.996.258-31', 'fernanda.reis@gmail.com', 'Avenida Rio Negro, 500');
INSERT INTO TIPO_PRODUTO_FINANCEIRO(DESCRICAO) VALUES ('Conta Poupança');
INSERT INTO CONTA(NUMERO_CONTA, AGENCIA, SENHA, FK_CLIENTE_ID) VALUES (123456, 1234, 'fer123', 1);
INSERT INTO PRODUTO_FINANCEIRO(VALOR, FK_NUMERO_CONTA, FK_AGENCIA, FK_TIPO_PRODUTO_FINANCEIRO_ID) VALUES (200, 123456, 1234, 1);

