
CREATE TABLE TIPO_PRODUTO_FINANCEIRO(
    TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_PRODUTO_FINANCEIRO PRIMARY KEY (TIPO_PRODUTO_FINANCEIRO_ID)
);
