CREATE TABLE PRODUTO_FINANCEIRO(
    PRODUTO_FINANCEIRO_ID SERIAL NOT NULL,
    VALOR FLOAT,
    FK_NUMERO_CONTA INTEGER NOT NULL,
    FK_AGENCIA INTEGER NOT NULL,
    FK_TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL,
    CONSTRAINT PK_PRODUTO_FINANCEIERO PRIMARY KEY(PRODUTO_FINANCEIRO_ID)
);

ALTER TABLE PRODUTO_FINANCEIRO ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_TIPO_PRODUTO_FINANCEIRO FOREIGN KEY (FK_TIPO_PRODUTO_FINANCEIRO_ID) REFERENCES TIPO_PRODUTO_FINANCEIRO (TIPO_PRODUTO_FINANCEIRO_ID);
ALTER TABLE PRODUTO_FINANCEIRO ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_CONTA FOREIGN KEY (FK_NUMERO_CONTA , FK_AGENCIA) REFERENCES CONTA(NUMERO_CONTA,AGENCIA);

