
CREATE TABLE TRANSACAO(
    TRANSACAO_ID INTEGER NOT NULL AUTO_INCREMENT,
    DATA_TRANSACAO DATE NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR FLOAT NOT NULL,
    FK_PRODUTO_FINANCEIRO INTEGER,
    CONSTRAINT PK_TRANSACAO PRIMARY KEY(TRANSACAO_ID)
    
);

ALTER TABLE TRANSACAO ADD CONSTRAINT FK_TRANSACAO_PRODUTO_FINANCEIRO FOREIGN KEY (FK_PRODUTO_FINANCEIRO) REFERENCES PRODUTO_FINANCEIRO(PRODUTO_FINANCEIRO_ID);
