INSERT INTO CLIENTE(NOME, CPF, EMAIL, ENDERECO) VALUES ('Fernanda', '444.996.258-31', 'fernanda.reis@gmail.com', 'Avenida Rio Negro, 500');
INSERT INTO TIPO_PRODUTO_FINANCEIRO(DESCRICAO) VALUES ('Conta Poupança');
INSERT INTO CONTA(NUMERO_CONTA, AGENCIA, SENHA, FK_CLIENTE_ID) VALUES (123456, 1234, 'fer123', 1);
INSERT INTO PRODUTO_FINANCEIRO(VALOR, FK_NUMERO_CONTA, FK_AGENCIA, FK_TIPO_PRODUTO_FINANCEIRO_ID) VALUES (200, 123456, 1234, 1);